#Range of image augumentation for labels
BRIGHTNESS = (.1, 2)
SATURATION = (.1, 2)
CONTRAST = (.1, 2)
SHARPNESS = (-4, 4)

NORMAL_BRIGHTNESS = 1
NORMAL_SATURATION = 1 
NORMAL_CONTRAST = 1
NORMAL_SHARPNESS = 1

MAX_BRIGHTNESS_LABEL = BRIGHTNESS[1] - NORMAL_BRIGHTNESS
MIN_BRIGHTNESS_LABEL = BRIGHTNESS[0] - NORMAL_BRIGHTNESS

MAX_SATURATION_LABEL = SATURATION[1] - NORMAL_SATURATION
MIN_SATURATION_LABEL = SATURATION[0] - NORMAL_SATURATION

MAX_CONTRAST_LABEL = CONTRAST[1] - NORMAL_CONTRAST
MIN_CONTRAST_LABEL = CONTRAST[0] - NORMAL_CONTRAST

MAX_SHARPNESS_LABEL = SHARPNESS[1] - NORMAL_SHARPNESS
MIN_SHARPNESS_LABEL = SHARPNESS[0] - NORMAL_SHARPNESS
